### ISSUE TITLE
License for the sample code

### ISSUE THREAD

**Issue by kjellander-unity** [stottle-uk/IntegrationTestingWithIdentityServer#1]
Thanks for nice examples on how to test identity server in isolation.
I'm wondering if you would mind adding some permissive license, like MIT, to the code so I can use it in my project?

**Comment by stottle-uk** [comment]
Hi @hkjellander 

I've added a license file - apologies for the delay

**Comment by kjellander-unity** [comment]
Thank you @stottle-uk!
